import PrimeVue from 'primevue/config'
import ToastService from 'primevue/toastservice'
import ConfirmationService from 'primevue/confirmationservice'
import Tooltip from 'primevue/tooltip'
import Aura from '@primeuix/themes/aura'
import 'primeicons/primeicons.css'

// Locale bahasa Indonesia untuk teks bawaan komponen PrimeVue.
export const localeId = {
  startsWith: 'Diawali',
  contains: 'Mengandung',
  notContains: 'Tidak mengandung',
  endsWith: 'Diakhiri',
  equals: 'Sama dengan',
  notEquals: 'Tidak sama dengan',
  noFilter: 'Tanpa filter',
  lt: 'Kurang dari',
  lte: 'Kurang dari atau sama dengan',
  gt: 'Lebih dari',
  gte: 'Lebih dari atau sama dengan',
  dateIs: 'Tanggal adalah',
  dateIsNot: 'Tanggal bukan',
  dateBefore: 'Tanggal sebelum',
  dateAfter: 'Tanggal sesudah',
  clear: 'Bersihkan',
  apply: 'Terapkan',
  matchAll: 'Cocok semua',
  matchAny: 'Cocok salah satu',
  addRule: 'Tambah aturan',
  removeRule: 'Hapus aturan',
  accept: 'Ya',
  reject: 'Tidak',
  choose: 'Pilih',
  upload: 'Unggah',
  cancel: 'Batal',
  completed: 'Selesai',
  pending: 'Menunggu',
  fileSizeTypes: ['B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'],
  dayNames: ['Minggu', 'Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu'],
  dayNamesShort: ['Min', 'Sen', 'Sel', 'Rab', 'Kam', 'Jum', 'Sab'],
  dayNamesMin: ['Mg', 'Sn', 'Sl', 'Rb', 'Km', 'Jm', 'Sb'],
  monthNames: [
    'Januari',
    'Februari',
    'Maret',
    'April',
    'Mei',
    'Juni',
    'Juli',
    'Agustus',
    'September',
    'Oktober',
    'November',
    'Desember',
  ],
  monthNamesShort: [
    'Jan',
    'Feb',
    'Mar',
    'Apr',
    'Mei',
    'Jun',
    'Jul',
    'Agu',
    'Sep',
    'Okt',
    'Nov',
    'Des',
  ],
  chooseYear: 'Pilih tahun',
  chooseMonth: 'Pilih bulan',
  chooseDate: 'Pilih tanggal',
  prevDecade: 'Dekade sebelumnya',
  nextDecade: 'Dekade berikutnya',
  prevYear: 'Tahun sebelumnya',
  nextYear: 'Tahun berikutnya',
  prevMonth: 'Bulan sebelumnya',
  nextMonth: 'Bulan berikutnya',
  prevHour: 'Jam sebelumnya',
  nextHour: 'Jam berikutnya',
  prevMinute: 'Menit sebelumnya',
  nextMinute: 'Menit berikutnya',
  prevSecond: 'Detik sebelumnya',
  nextSecond: 'Detik berikutnya',
  am: 'AM',
  pm: 'PM',
  today: 'Hari ini',
  weekHeader: 'Mg',
  firstDayOfWeek: 1,
  showMonthAfterYear: false,
  dateFormat: 'dd/mm/yy',
  weak: 'Lemah',
  medium: 'Sedang',
  strong: 'Kuat',
  passwordPrompt: 'Masukkan password',
  emptyFilterMessage: 'Tidak ada hasil',
  searchMessage: '{0} hasil tersedia',
  selectionMessage: '{0} item dipilih',
  emptySelectionMessage: 'Tidak ada item dipilih',
  emptySearchMessage: 'Tidak ada hasil',
  fileChosenMessage: '{0} berkas',
  noFileChosenMessage: 'Tidak ada berkas dipilih',
  emptyMessage: 'Tidak ada data',
  aria: {
    trueLabel: 'Ya',
    falseLabel: 'Tidak',
    nullLabel: 'Tidak dipilih',
    star: '1 bintang',
    stars: '{star} bintang',
    selectAll: 'Semua item dipilih',
    unselectAll: 'Semua item batal dipilih',
    close: 'Tutup',
    previous: 'Sebelumnya',
    next: 'Berikutnya',
    navigation: 'Navigasi',
    scrollTop: 'Gulir ke atas',
    moveTop: 'Pindah ke atas',
    moveUp: 'Pindah naik',
    moveDown: 'Pindah turun',
    moveBottom: 'Pindah ke bawah',
    moveToTarget: 'Pindah ke tujuan',
    moveToSource: 'Pindah ke sumber',
    moveAllToTarget: 'Pindahkan semua ke tujuan',
    moveAllToSource: 'Pindahkan semua ke sumber',
    pageLabel: 'Halaman {page}',
    firstPageLabel: 'Halaman pertama',
    lastPageLabel: 'Halaman terakhir',
    nextPageLabel: 'Halaman berikutnya',
    prevPageLabel: 'Halaman sebelumnya',
    rowsPerPageLabel: 'Baris per halaman',
    jumpToPageDropdownLabel: 'Lompat ke halaman',
    jumpToPageInputLabel: 'Lompat ke halaman',
    selectRow: 'Baris dipilih',
    unselectRow: 'Baris batal dipilih',
    expandRow: 'Baris dibuka',
    collapseRow: 'Baris ditutup',
    showFilterMenu: 'Tampilkan menu filter',
    hideFilterMenu: 'Sembunyikan menu filter',
    filterOperator: 'Operator filter',
    filterConstraint: 'Batasan filter',
    editRow: 'Ubah baris',
    saveEdit: 'Simpan',
    cancelEdit: 'Batal',
    listView: 'Tampilan daftar',
    gridView: 'Tampilan kisi',
    slide: 'Slide',
    slideNumber: '{slideNumber}',
    zoomImage: 'Perbesar gambar',
    zoomIn: 'Perbesar',
    zoomOut: 'Perkecil',
    rotateRight: 'Putar kanan',
    rotateLeft: 'Putar kiri',
    listLabel: 'Daftar pilihan',
  },
}

export function installPrimeVue(app) {
  app.use(PrimeVue, {
    theme: {
      preset: Aura,
      options: {
        // Mode gelap dinonaktifkan agar tampilan konsisten.
        darkModeSelector: false,
      },
    },
    locale: localeId,
    ripple: false,
  })
  app.use(ToastService)
  app.use(ConfirmationService)
  app.directive('tooltip', Tooltip)
}
